NMAP_RPI_DIR=/home/pi/nmap-rpi
TIMESTAMP=$(date +"%Y-%m-%d-%H:%M")
OUTPUT_PATH="$NMAP_RPI_DIR/data/nmap-os-$TIMESTAMP"
XML_OUTPUT_PATH="$OUTPUT_PATH.xml"
TXT_OUTPUT_PATH="$OUTPUT_PATH.txt"
IP_RANGE='192.168.0.0/24'

nmap -O $IP_RANGE -oX $XML_OUTPUT_PATH
nmap -O $IP_RANGE -o $TXT_OUTPUT_PATH
